apiVersion: v1
kind: Service
metadata:
  name: printaura
  labels:
    app: printaura
spec:
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: printaura
    tier: frontend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pa-pv-claim
  labels:
    app: printaura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: printaura
  labels:
    app: printaura
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: printaura
        tier: frontend
    spec:
      containers:
      - image: buddy/printaura:latest
        name: printaura
        env:
        - name: printaura_DB_HOST
          value: printaura-mysql
        - name: printaura_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: printaura
        volumeMounts:
        - name: printaura-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: printaura-persistent-storage
        persistentVolumeClaim:
          claimName: pa-pv-claim
